//
//  ProblemDispatch.swift
//  Tangram
//
//  Auto-generated by gen_tests.py. Do not edit manually.
//

enum ProblemRunner {
    static func run(_ id: Int) {
        let sol = Solution()
        let cases = loadTestCases(id)
        guard !cases.isEmpty else {
            print("No test cases for problem #\(id). Run: python3 Scripts/gen_tests.py \(id)")
            return
        }

        print("--- [\(id)] Non-overlapping Intervals ---")
        var passed = 0, failed = 0

        for (i, tc) in cases.enumerated() {
            check(sol.eraseOverlapIntervals(tc.intArray2D(0)), tc.expectedInt, "Case \(i + 1)", &passed, &failed)
        }

        print("\(passed + failed) tests: \(passed) passed, \(failed) failed")
    }

    private static func check<T: Equatable>(_ got: T, _ expected: T, _ label: String, _ passed: inout Int, _ failed: inout Int) {
        if got == expected {
            passed += 1
            print("  \(label) pass")
        } else {
            failed += 1
            print("  \(label) FAIL  got: \(got), expected: \(expected)")
        }
    }

    private static func checkAccuracy(_ got: Double, _ expected: Double, accuracy: Double, _ label: String, _ passed: inout Int, _ failed: inout Int) {
        if abs(got - expected) <= accuracy {
            passed += 1
            print("  \(label) pass")
        } else {
            failed += 1
            print("  \(label) FAIL  got: \(got), expected: \(expected)")
        }
    }
}
